New Attribute i
adfinis-sygroup/check-ssl pull request #3
Opened 2017-03-24 09:14 UTC by hotstepper13

Allows connecting to an IP instead of dns to check multiple servers
behind loadbalancer or reverse proxy with their own certificate

2017-03-30 11:47 UTC, karras requested changes
Thanks for the PR, looks great! Could you please fix the alignments? Then I'll merge it.

2017-03-30 11:47 UTC, karras commented on check_ssl.sh
> +    i) #set ip to connect (instead of dns)
Please align this case with the other ones.

2017-03-30 11:47 UTC, karras commented on check_ssl.sh
> +		HOST_CHECK=$(openssl s_client -servername "${HOST}" -connect "${IP}":"${PORT}" -starttls "${PROTOCOL}" 2>&- | openssl x509 -enddate -noout)
This line should be aligned as well. :)

2017-03-30 13:37 UTC, hotstepper13 commented
Sorry not sure what to do. On my System(s) (windows and Mac with eclipse) the indenting looks good. Feel free to change it in order to match your requirements. Most probably this may because lacking git skills on my side to I apologize for any inconvenience.

2017-04-04 15:56 UTC, luk43 commented
Hi @hotstepper13 
You can fill in the ip address of the server just like you would for the hostname.
It works the same way. No changes needed.

2017-04-04 18:14 UTC, hotstepper13 commented
One hint: If you validate a certificate by common name e.g. www.example.com but let the check run from localhost, it might make sense to connect with ip 127.0.0.1 instead of a regular dns entry.

Especially if you have (for instance) 3 Servers behind a (L4) loadbalancer and you want to make sure that each server has the correct certificate installed. Then you let the check run on each server instead of the dns record.

That was the intention for the change and for this use case the change WAS needed :)

2017-04-05 15:03 UTC, luk43 commented
merged now through [this commit](https://github.com/adfinis-sygroup/check-ssl/commit/172faae296879c5003584e78490b265bbdf92b7a).
Thanks @hotstepper13 for explaining the problem one more time. ^^
cheers

2017-04-05 15:03 UTC, closed without merging